[package]
name = "mm-lean"
version = "0.1"
lean_version = "master"

[dependencies]
mathematica = {git = "https://github.com/rlewis1988/mathematica", rev = "e94c6824b512fc62923d4476e68f40de56801c21"}
