[package]
name = "mm-lean"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathematica = {git = "https://github.com/rlewis1988/mathematica", rev = "c41732fc1e3310322123c027bcfa5c7ccda0e3ea"}
mathlib = {git = "https://github.com/leanprover-community/mathlib.git", rev = "7221900b8b0da754937d0c87a31cf7dab74f296e"}
