[package]
name = "mm-lean"
version = "0.1"
lean_version = "master"

[dependencies]
mathematica = {git = "https://github.com/rlewis1988/mathematica", rev = "6fbd21b35eca1484b883cc40f235aa9c14a38fb5"}
